### ISSUE TITLE
Lab2 is giving 404

### ISSUE THREAD

**Issue by punitdarji** [ZeddYu/HTTP-Smuggling-Lab#1]
I have setup your lab as given instruction. I am using `ubuntu 18.04 LTS`. In ubuntu, lab2 is showing `phusion/baseimage` manifest not found then I have setup lab on my local machine windows, when I check with `check.sh `  the response is
```
HTTP/1.1 404 Not Found on Accelerator
Date: Wed, 21 Oct 2020 06:38:56 GMT
Connection: close
Server: ATS/7.1.1
Cache-Control: no-store
Content-Type: text/html
Content-Language: en
Content-Length: 297
```
could you possibly guide me how to resolve this issue?

**Comment by ZeddYu** [comment]
I have updated the dockerfile in lab2. You can add the manifestof `phusion/baseimage:master` to fix the manifest not found error. If you still have other issues, please let me know. :)

**Comment by craig1122321** [comment]
Hi @ZeddYu 
I have the same issue, but, I already clone the latest version. And check `phusion/baseimage:master` is in ats7.Dockerfile.
the response of check.sh is

> HTTP/1.1 200 OK
> </pre>HTTP/1.1 404 Not Found on Accelerator
> HTTP/1.1 404 Not Found on Accelerator
How do I resolve this issue?
Thanks

**Comment by ZeddYu** [comment]
Sorry. I can't reporduce your issue. Could you provide detailed description? @craig1122321 

> Hi @ZeddYu
> I have the same issue, but, I already clone the latest version. And check `phusion/baseimage:master` is in ats7.Dockerfile.
> the response of check.sh is
> 
> > HTTP/1.1 200 OK
> > HTTP/1.1 404 Not Found on Accelerator
> > HTTP/1.1 404 Not Found on Accelerator
> > How do I resolve this issue?
> > Thanks

**Comment by craig1122321** [comment]
@ZeddYu I use MacOS, download the latest version of docker, and clone the latest version of lab
do docker-compose up shows:

> amp_1  | 2021-02-09 05:13:26,945 INFO spawned: 'apache2' with pid 28
> lamp_1  | 2021-02-09 05:13:26,948 INFO spawned: 'mysqld' with pid 29
> lnmp_1  |    ...done.
> lnmp_1  |  * Restarting nginx nginx
> lnmp_1  |    ...done.
> lamp_1  | 2021-02-09 05:13:28,245 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> lamp_1  | 2021-02-09 05:13:28,246 INFO success: mysqld entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> lnmp_1  |  * Restarting daemon monitor monit
> lnmp_1  | start-stop-daemon: warning: failed to kill 433: No such process
> lnmp_1  |    ...done.
> lnmp_1  | ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'%'

and chmod +x check.sh | ./check.sh |grep HTTP shows:

> HTTP/1.1 200 OK
> </pre>HTTP/1.1 404 Not Found on Accelerator
> HTTP/1.1 404 Not Found on Accelerator

**Comment by ZeddYu** [comment]
Hi. I have upadted the docker images of lab2. Please pull the new commit and try again. If you have any problems, feel free to contact me.

**Comment by ZeddYu** [comment]
> @ZeddYu I use MacOS, download the latest version of docker, and clone the latest version of lab
> do docker-compose up shows:
> 
> > amp_1  | 2021-02-09 05:13:26,945 INFO spawned: 'apache2' with pid 28
> > lamp_1  | 2021-02-09 05:13:26,948 INFO spawned: 'mysqld' with pid 29
> > lnmp_1  |    ...done.
> > lnmp_1  |  * Restarting nginx nginx
> > lnmp_1  |    ...done.
> > lamp_1  | 2021-02-09 05:13:28,245 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> > lamp_1  | 2021-02-09 05:13:28,246 INFO success: mysqld entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> > lnmp_1  |  * Restarting daemon monitor monit
> > lnmp_1  | start-stop-daemon: warning: failed to kill 433: No such process
> > lnmp_1  |    ...done.
> > lnmp_1  | ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'%'
> 
> and chmod +x check.sh | ./check.sh |grep HTTP shows:
> 
> > HTTP/1.1 200 OK
> > HTTP/1.1 404 Not Found on Accelerator
> > HTTP/1.1 404 Not Found on Accelerator

Hi. I have upadted the docker images of lab2. Please pull the new commit and try again. If you have any problems, feel free to contact me. @craig1122321

**Comment by craig1122321** [comment]
@ZeddYu Thanks for your update, but the problem still exists.
maybe I should give you more detail:

> docker-compose up
> Starting lab2_lamp_1 ... done
> Starting lab2_lnmp_1 ... done
> Starting lab2_ats7_1 ... done
> Attaching to lab2_lnmp_1, lab2_lamp_1, lab2_ats7_1
> lamp_1  | Updating for PHP 7.4
> lnmp_1  | Reading package lists...
> lamp_1  | Replacing CLI php.ini values
> lnmp_1  | Building dependency tree...
> lamp_1  | Editing APACHE_RUN_GROUP environment variable
> lnmp_1  | Reading state information...
> lamp_1  | Editing phpmyadmin config
> lnmp_1  | ENV :: HOSTNAME => d47f299729eb
> lamp_1  | Setting up MySQL directories
> lnmp_1  | ENV :: PWD => /
> lamp_1  | Allowing Apache/PHP to write to the app
> lnmp_1  | ENV :: HOME => /root
> lamp_1  | Allowing Apache/PHP to write to MySQL
> lamp_1  | Editing MySQL config
> lnmp_1  | ENV :: SHLVL => 1
> lnmp_1  | ENV :: PATH => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> lamp_1  | => Using an existing volume of MySQL
> lamp_1  | Starting supervisord
> lnmp_1  |  * Restarting periodic command scheduler cron
> lamp_1  | 2021-02-09 07:39:43,454 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
> lamp_1  | 2021-02-09 07:39:43,454 INFO Included extra file "/etc/supervisor/conf.d/supervisord-apache2.conf" during parsing
> lamp_1  | 2021-02-09 07:39:43,454 INFO Included extra file "/etc/supervisor/conf.d/supervisord-mysqld.conf" during parsing
> lnmp_1  |  * Stopping periodic command scheduler cron
> lamp_1  | 2021-02-09 07:39:43,460 INFO RPC interface 'supervisor' initialized
> lamp_1  | 2021-02-09 07:39:43,461 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> lamp_1  | 2021-02-09 07:39:43,461 INFO supervisord started with pid 1
> lnmp_1  | /sbin/start-stop-daemon: warning: failed to kill 85: No such process
> lnmp_1  |    ...done.
> lnmp_1  |  * Starting periodic command scheduler cron
> lnmp_1  |    ...done.
> lnmp_1  |  * Restarting PHP 7.1 FastCGI Process Manager php-fpm7.1
> lnmp_1  |    ...done.
> lnmp_1  |  * Stopping MariaDB database server mysqld
> lnmp_1  |    ...done.
> lnmp_1  |  * Starting MariaDB database server mysqld
> lnmp_1  |    ...done.
> lnmp_1  |  * Restarting nginx nginx
> lamp_1  | 2021-02-09 07:39:44,463 INFO spawned: 'apache2' with pid 28
> lamp_1  | 2021-02-09 07:39:44,465 INFO spawned: 'mysqld' with pid 29
> lnmp_1  |    ...done.
> lamp_1  | 2021-02-09 07:39:45,769 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> lamp_1  | 2021-02-09 07:39:45,769 INFO success: mysqld entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> lnmp_1  |  * Restarting daemon monitor monit
> lnmp_1  | start-stop-daemon: warning: failed to kill 444: No such process
> lnmp_1  |    ...done.
> lnmp_1  | ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'%'
> lnmp_1  | 172.24.0.1 - - [09/Feb/2021:07:40:00 +0000] "GET / HTTP/1.1" 499 0 "-" "-"

and the check.sh:

> chmod +x check.sh;./check.sh|grep HTTP
> HTTP/1.1 200 OK
> </pre>HTTP/1.1 404 Not Found on Accelerator
> HTTP/1.1 404 Not Found on Accelerator

**Comment by ZeddYu** [comment]
> @ZeddYu Thanks for your update, but the problem still exists.
> maybe I should give you more detail:
> 
> > docker-compose up
> > Starting lab2_lamp_1 ... done
> > Starting lab2_lnmp_1 ... done
> > Starting lab2_ats7_1 ... done
> > Attaching to lab2_lnmp_1, lab2_lamp_1, lab2_ats7_1
> > lamp_1  | Updating for PHP 7.4
> > lnmp_1  | Reading package lists...
> > lamp_1  | Replacing CLI php.ini values
> > lnmp_1  | Building dependency tree...
> > lamp_1  | Editing APACHE_RUN_GROUP environment variable
> > lnmp_1  | Reading state information...
> > lamp_1  | Editing phpmyadmin config
> > lnmp_1  | ENV :: HOSTNAME => d47f299729eb
> > lamp_1  | Setting up MySQL directories
> > lnmp_1  | ENV :: PWD => /
> > lamp_1  | Allowing Apache/PHP to write to the app
> > lnmp_1  | ENV :: HOME => /root
> > lamp_1  | Allowing Apache/PHP to write to MySQL
> > lamp_1  | Editing MySQL config
> > lnmp_1  | ENV :: SHLVL => 1
> > lnmp_1  | ENV :: PATH => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> > lamp_1  | => Using an existing volume of MySQL
> > lamp_1  | Starting supervisord
> > lnmp_1  |  * Restarting periodic command scheduler cron
> > lamp_1  | 2021-02-09 07:39:43,454 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
> > lamp_1  | 2021-02-09 07:39:43,454 INFO Included extra file "/etc/supervisor/conf.d/supervisord-apache2.conf" during parsing
> > lamp_1  | 2021-02-09 07:39:43,454 INFO Included extra file "/etc/supervisor/conf.d/supervisord-mysqld.conf" during parsing
> > lnmp_1  |  * Stopping periodic command scheduler cron
> > lamp_1  | 2021-02-09 07:39:43,460 INFO RPC interface 'supervisor' initialized
> > lamp_1  | 2021-02-09 07:39:43,461 CRIT Server 'unix_http_server' running without any HTTP authentication checking
> > lamp_1  | 2021-02-09 07:39:43,461 INFO supervisord started with pid 1
> > lnmp_1  | /sbin/start-stop-daemon: warning: failed to kill 85: No such process
> > lnmp_1  |    ...done.
> > lnmp_1  |  * Starting periodic command scheduler cron
> > lnmp_1  |    ...done.
> > lnmp_1  |  * Restarting PHP 7.1 FastCGI Process Manager php-fpm7.1
> > lnmp_1  |    ...done.
> > lnmp_1  |  * Stopping MariaDB database server mysqld
> > lnmp_1  |    ...done.
> > lnmp_1  |  * Starting MariaDB database server mysqld
> > lnmp_1  |    ...done.
> > lnmp_1  |  * Restarting nginx nginx
> > lamp_1  | 2021-02-09 07:39:44,463 INFO spawned: 'apache2' with pid 28
> > lamp_1  | 2021-02-09 07:39:44,465 INFO spawned: 'mysqld' with pid 29
> > lnmp_1  |    ...done.
> > lamp_1  | 2021-02-09 07:39:45,769 INFO success: apache2 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> > lamp_1  | 2021-02-09 07:39:45,769 INFO success: mysqld entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> > lnmp_1  |  * Restarting daemon monitor monit
> > lnmp_1  | start-stop-daemon: warning: failed to kill 444: No such process
> > lnmp_1  |    ...done.
> > lnmp_1  | ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'root'@'%'
> > lnmp_1  | 172.24.0.1 - - [09/Feb/2021:07:40:00 +0000] "GET / HTTP/1.1" 499 0 "-" "-"
> 
> and the check.sh:
> 
> > chmod +x check.sh;./check.sh|grep HTTP
> > HTTP/1.1 200 OK
> > HTTP/1.1 404 Not Found on Accelerator
> > HTTP/1.1 404 Not Found on Accelerator

@craig1122321  Nope. You should run `git pull` first and then run `docker-compose up -d --build`. And it would be better to check the first line of lamp.Dockerfile is `FROM php:7.4-apache-buster`. I doesn't use mysqld in the new version but your error log turn out there is a mysqld error. So I think you still use the old version. Try the new version I think it will work.

**Comment by Sh1Yo** [comment]
I faced the same issue on a fresh installation while trying to connect to lamp&lnmp via apache traffic. Can you check it @ZeddYu ?
```
Linux arch 5.12.9-arch1-1 #1 SMP PREEMPT Thu, 03 Jun 2021 11:36:13 +0000 x86_64 GNU/Linux
Docker version 20.10.7, build f0df35096d
```

```
Starting lab2_lamp_1 ... done
Starting lab2_lnmp_1 ... done
Starting lab2_ats7_1 ... done
Attaching to lab2_lamp_1, lab2_lnmp_1, lab2_ats7_1
lnmp_1  | 2021-07-15 16:02:04,859 INFO Set uid to user 0 succeeded
lamp_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.2. Set the 'ServerName' directive globally to suppress this message
lamp_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.2. Set the 'ServerName' directive globally to suppress this message
lamp_1  | [Thu Jul 15 16:02:04.729865 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.21 configured -- resuming normal operations
lamp_1  | [Thu Jul 15 16:02:04.729915 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
lnmp_1  | Unlinking stale socket /tmp/supervisor.sock
lnmp_1  | 2021-07-15 16:02:05,170 INFO RPC interface 'supervisor' initialized
lnmp_1  | 2021-07-15 16:02:05,171 INFO supervisord started with pid 13
lnmp_1  | 2021-07-15 16:02:06,175 INFO spawned: 'stdout' with pid 16
lnmp_1  | 2021-07-15 16:02:06,179 INFO spawned: 'php-fpm7' with pid 17
lnmp_1  | 2021-07-15 16:02:06,185 INFO spawned: 'nginx' with pid 18
lnmp_1  | 2021-07-15 16:02:07,283 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
lnmp_1  | 2021-07-15 16:02:07,284 INFO success: php-fpm7 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
lnmp_1  | 2021-07-15 16:02:07,284 INFO success: nginx entered RUNNING state, process has stayed
```

**Comment by ZeddYu** [comment]
> I faced the same issue on a fresh installation while trying to connect to lamp&lnmp via apache traffic. Can you check it @ZeddYu ?
> 
> ```
> Linux arch 5.12.9-arch1-1 #1 SMP PREEMPT Thu, 03 Jun 2021 11:36:13 +0000 x86_64 GNU/Linux
> Docker version 20.10.7, build f0df35096d
> ```
> 
> ```
> Starting lab2_lamp_1 ... done
> Starting lab2_lnmp_1 ... done
> Starting lab2_ats7_1 ... done
> Attaching to lab2_lamp_1, lab2_lnmp_1, lab2_ats7_1
> lnmp_1  | 2021-07-15 16:02:04,859 INFO Set uid to user 0 succeeded
> lamp_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.2. Set the 'ServerName' directive globally to suppress this message
> lamp_1  | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.19.0.2. Set the 'ServerName' directive globally to suppress this message
> lamp_1  | [Thu Jul 15 16:02:04.729865 2021] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.21 configured -- resuming normal operations
> lamp_1  | [Thu Jul 15 16:02:04.729915 2021] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
> lnmp_1  | Unlinking stale socket /tmp/supervisor.sock
> lnmp_1  | 2021-07-15 16:02:05,170 INFO RPC interface 'supervisor' initialized
> lnmp_1  | 2021-07-15 16:02:05,171 INFO supervisord started with pid 13
> lnmp_1  | 2021-07-15 16:02:06,175 INFO spawned: 'stdout' with pid 16
> lnmp_1  | 2021-07-15 16:02:06,179 INFO spawned: 'php-fpm7' with pid 17
> lnmp_1  | 2021-07-15 16:02:06,185 INFO spawned: 'nginx' with pid 18
> lnmp_1  | 2021-07-15 16:02:07,283 INFO success: stdout entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> lnmp_1  | 2021-07-15 16:02:07,284 INFO success: php-fpm7 entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
> lnmp_1  | 2021-07-15 16:02:07,284 INFO success: nginx entered RUNNING state, process has stayed
> ```

It seems it is due to the links of docker compose is deprecated now.
https://docs.docker.com/compose/compose-file/compose-file-v3/#links

I will correct this in this repo today. But need some time.

**Comment by ZeddYu** [comment]
@Sh1Yo 
Done. I think I have fixed the issue. I use docker compose file v3.9. And does not use links prop any more.
You could update your docker and pull the latest repo to try. :)

**Comment by Sh1Yo** [comment]
Thanks, it is working now.
